[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
ffi = true
ast = true
build_info = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
